export const indiaLocations = [
  "Ahmedabad, Gujarat",
  "Bengaluru, Karnataka",
  "Bhopal, Madhya Pradesh",
  "Bhubaneswar, Odisha",
  "Chandigarh, Chandigarh",
  "Chennai, Tamil Nadu",
  "Delhi, Delhi",
  "Gurugram, Haryana",
  "Hyderabad, Telangana",
  "Indore, Madhya Pradesh",
  "Jaipur, Rajasthan",
  "Kochi, Kerala",
  "Kolkata, West Bengal",
  "Lucknow, Uttar Pradesh",
  "Mumbai, Maharashtra",
  "Noida, Uttar Pradesh",
  "Patna, Bihar",
  "Pune, Maharashtra",
  "Surat, Gujarat",
] as const;
